### ISSUE TITLE
Text: fix space between helpText & input box

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#1271]
Reference: https://github.com/razorpay/blade/pull/1160#issuecomment-1567004364

**Comment by harshsinghatz** [comment]
ref: https://github.com/razorpay/blade/pull/1160#event-9469370343
Right now the helpText & the maxChar limiter text is shifted a bit downwards:
![image](https://github.com/razorpay/blade/assets/51085015/19cadbc3-aff9-461b-ad59-6ff4269b686d)

It should be like this:
![image](https://github.com/razorpay/blade/assets/51085015/00cf6819-fafa-45fb-aeac-b552267da86c)

**Comment by kamleshchandnani** [comment]
Fixed in: #1160

**Comment by anuraghazra** [comment]
This is still present this alignment issue is different that what was originally fixed in #1160 

![](https://user-images.githubusercontent.com/35374649/241720383-8b32f7d8-d6ad-48dd-a650-5995a16f8d70.png)
