### ISSUE TITLE
Improve blade coverage calculation method

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1388]
The Blade coverage script considers any element with a parent containing `data-blade-component` attribute as a Blade component. This became an issue with the introduction of the Box component since it's by design meant to be the parent component in most places, automatically marking everything inside it as a Blade component.

This can be reproduced by manually adding a data-blade attribute to just one parent level node to an app not using Blade:

https://github.com/razorpay/blade/assets/29686866/ce0ffa16-dd52-4822-bba7-597b2434ae63

This makes it hard to identify design system deviations because the parent level Box component masks all custom built components inside it and reports full Blade coverage.

**Comment by anuraghazra** [comment]
@cseas this is a known issue and we have already rolled out Phase-1 to fix this issue. 

https://github.com/razorpay/blade/pull/1342

We have added data-attributes to the leaf nodes to calculate those also and next we will update the coverage-script to prevent counting non-blade child nodes as Blade nodes.

**Comment by chaitanyadeorukhkar** [comment]
Closing this since this is resolved with #1342

**Comment by cseas** [comment]
Not resolved. The bug in the video I posted above is still reproducible, which means the coverage will show up as close to 100% if we just add a single Box wrapper around the whole app. Maybe the Chrome extension needs to be updated? What's the recommended way to find coverage of a page?

**Comment by anuraghazra** [comment]
Will be released the fix this week.

**Comment by anuraghazra** [comment]
@cseas did we upgrade frontend website to latest version of blade?

**Comment by cseas** [comment]
Yes, it's on Blade v9.0.3

**Comment by anuraghazra** [comment]
This has been resolved and [released](https://razorpay.slack.com/archives/C01H13RTF8V/p1690442157047529?thread_ts=1688456672.342719&cid=C01H13RTF8V):
